import { Alert, Button, Card, Empty, Segmented, Skeleton, Space } from 'antd';
import React, { useCallback, useEffect, useRef, useState } from 'react';
import type { TaiwanStockKLineResponse } from '../services/api';

declare global { interface Window { LightweightCharts?: { createChart:(container:HTMLElement,options:Record<string,unknown>)=>ChartApi; ColorType:{Solid:string}; CandlestickSeries?:unknown; HistogramSeries?:unknown; }; } }
type Candle={time:string;open:number;high:number;low:number;close:number}; type Histogram={time:string;value:number;color?:string};
type SeriesApi<T>={setData:(data:T[])=>void}; type ChartApi={addCandlestickSeries?:(o:Record<string,unknown>)=>SeriesApi<Candle>;addHistogramSeries?:(o:Record<string,unknown>)=>SeriesApi<Histogram>;addSeries?:<T>(d:unknown,o:Record<string,unknown>)=>SeriesApi<T>;timeScale:()=>{fitContent:()=>void};remove:()=>void;applyOptions?:(o:Record<string,unknown>)=>void};
const SCRIPT='https://unpkg.com/lightweight-charts/dist/lightweight-charts.standalone.production.js';

interface Props { data: TaiwanStockKLineResponse | null; loading: boolean; error: string | null; }
const StockChart:React.FC<Props>=({data,loading,error})=>{
 const container=useRef<HTMLDivElement|null>(null); const chartRef=useRef<ChartApi|null>(null); const [interval,setInterval]=useState('日線'); const [range,setRange]=useState('6 個月'); const [indicators,setIndicators]=useState<string[]>([]); const [libraryError,setLibraryError]=useState<string|null>(null);
 const loadLibrary=useCallback(async()=>{if(window.LightweightCharts)return window.LightweightCharts; await new Promise<void>((resolve,reject)=>{const old=document.querySelector<HTMLScriptElement>(`script[src="${SCRIPT}"]`);if(old){old.addEventListener('load',()=>resolve(),{once:true});old.addEventListener('error',()=>reject(),{once:true});return;}const s=document.createElement('script');s.src=SCRIPT;s.async=true;s.onload=()=>resolve();s.onerror=()=>reject();document.body.appendChild(s)});if(!window.LightweightCharts)throw new Error();return window.LightweightCharts},[]);
 useEffect(()=>{let alive=true;const render=async()=>{if(!container.current||!data?.data.length)return;try{const lib=await loadLibrary();if(!alive)return;chartRef.current?.remove();const chart=lib.createChart(container.current,{height:430,layout:{background:{type:lib.ColorType.Solid,color:'#fff'},textColor:'#475569'},grid:{vertLines:{color:'#f1f5f9'},horzLines:{color:'#f1f5f9'}},rightPriceScale:{scaleMargins:{top:.08,bottom:.3}}});const candleOptions={upColor:'#ef4444',downColor:'#16a34a',wickUpColor:'#ef4444',wickDownColor:'#16a34a',borderVisible:false};const volumeOptions={priceFormat:{type:'volume'},priceScaleId:'',color:'#94a3b8'};const candles=chart.addCandlestickSeries?.(candleOptions)??chart.addSeries?.<Candle>(lib.CandlestickSeries,candleOptions);const volumes=chart.addHistogramSeries?.(volumeOptions)??chart.addSeries?.<Histogram>(lib.HistogramSeries,volumeOptions);if(!candles||!volumes)throw new Error();candles.setData(data.data.map(p=>({time:p.date.slice(0,10),open:p.open,high:p.high,low:p.low,close:p.close})));volumes.setData(data.data.map(p=>({time:p.date.slice(0,10),value:p.volume,color:p.close>=p.open?'#ef444477':'#16a34a77'})));chart.timeScale().fitContent();chartRef.current=chart;setLibraryError(null)}catch{setLibraryError('圖表元件載入失敗，請檢查網路連線後重試。')}};void render();return()=>{alive=false;chartRef.current?.remove();chartRef.current=null}},[data,loadLibrary]);
 const toggle=(value:string)=>setIndicators(current=>current.includes(value)?current.filter(x=>x!==value):[...current,value]);
 return <Card className="dashboard-card kline-card" title="K 線與成交量" extra={<span className="mock-label">TWSE 日資料</span>}><div className="chart-toolbar"><Segmented value={interval} onChange={value=>{setInterval(String(value));/* TODO Phase 2: aggregate daily data for weekly/monthly candles. */}} options={['日線','週線','月線']}/><Segmented value={range} onChange={value=>{setRange(String(value));/* TODO Phase 2: request periods beyond current six-month API. */}} options={['3 個月','6 個月','1 年','3 年']}/></div><Space wrap className="indicator-row">{['MA5','MA20','MA60','RSI','MACD','布林通道'].map(x=><Button key={x} size="small" type={indicators.includes(x)?'primary':'default'} onClick={()=>toggle(x)}>{x}</Button>)}</Space>{(error||libraryError)&&<Alert type="error" showIcon message={error||libraryError}/>} {loading?<Skeleton active paragraph={{rows:10}}/>:!data?.data.length?<Empty description="目前沒有 K 線資料"/>:<div className="chart-scroll"><div ref={container} className="chart-container"/></div>}</Card>;
};
export default StockChart;
