using Microsoft.EntityFrameworkCore;

namespace MyCMS.API.Data;

/// <summary>
/// Adds the property-management schema to legacy databases that were originally
/// provisioned outside EF Core migrations. This deliberately does not call
/// Database.Migrate(), because those databases do not have a complete migration
/// history even though the older tables already exist.
/// </summary>
public static class PropertyManagementSchemaInitializer
{
    public static void Initialize(AppDbContext context)
    {
        context.Database.ExecuteSqlRaw(
            """
            CREATE TABLE IF NOT EXISTS "PropertyManagementAreas" (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                "Name" text NOT NULL,
                "Location" text NOT NULL,
                "Category" integer NOT NULL,
                "QrToken" text NOT NULL,
                "CreatedAtUtc" timestamp with time zone NOT NULL,
                CONSTRAINT "PK_PropertyManagementAreas" PRIMARY KEY ("Id")
            );

            CREATE TABLE IF NOT EXISTS "PropertyCheckInLogs" (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                "AreaId" integer NOT NULL,
                "UserId" integer NOT NULL,
                "CheckInAtUtc" timestamp with time zone NOT NULL,
                "Note" text NULL,
                CONSTRAINT "PK_PropertyCheckInLogs" PRIMARY KEY ("Id")
            );

            CREATE UNIQUE INDEX IF NOT EXISTS "IX_PropertyManagementAreas_QrToken"
                ON "PropertyManagementAreas" ("QrToken");
            CREATE INDEX IF NOT EXISTS "IX_PropertyCheckInLogs_AreaId"
                ON "PropertyCheckInLogs" ("AreaId");
            CREATE INDEX IF NOT EXISTS "IX_PropertyCheckInLogs_UserId"
                ON "PropertyCheckInLogs" ("UserId");

            DO $initialize$
            BEGIN
                IF NOT EXISTS (
                    SELECT 1 FROM pg_constraint
                    WHERE conname = 'FK_PropertyCheckInLogs_PropertyManagementAreas_AreaId'
                ) THEN
                    ALTER TABLE "PropertyCheckInLogs"
                    ADD CONSTRAINT "FK_PropertyCheckInLogs_PropertyManagementAreas_AreaId"
                    FOREIGN KEY ("AreaId") REFERENCES "PropertyManagementAreas" ("Id")
                    ON DELETE CASCADE;
                END IF;

                IF NOT EXISTS (
                    SELECT 1 FROM pg_constraint
                    WHERE conname = 'FK_PropertyCheckInLogs_Users_UserId'
                ) THEN
                    ALTER TABLE "PropertyCheckInLogs"
                    ADD CONSTRAINT "FK_PropertyCheckInLogs_Users_UserId"
                    FOREIGN KEY ("UserId") REFERENCES "Users" ("Id")
                    ON DELETE CASCADE;
                END IF;
            END $initialize$;

            INSERT INTO "Roles" ("Id", "Name") VALUES
                (3, '機電人員'),
                (4, '清潔人員')
            ON CONFLICT ("Id") DO UPDATE SET "Name" = EXCLUDED."Name";
            """);
    }
}
